### ISSUE TITLE
Program crashes after longer duration

### ISSUE THREAD

**Issue by austinshinkle** [austinshinkle/OB_BreweryMonitorLog#1]
After many hours, the program writing data to the database with this error message.

Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Received from server: {"FermentationChamberTemp1_F": 77.2, "FermentationChamberTemp2_F": 77.1, "KegeratorTemp_F": 77.5, "KegWeightSensor1_PCT": -120, "KegWeightSensor2_PCT": 197}
{'FermentationChamberTemp1_F': 77.2, 'FermentationChamberTemp2_F': 77.1, 'KegeratorTemp_F': 77.5, 'KegWeightSensor1_PCT': -120, 'KegWeightSensor2_PCT': 197}
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
**Exception in thread Thread-1 (get_sensor_data):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 52, in get_sensor_data
    client_socket.connect((server_ip,server_port))
socket.gaierror: [Errno -3] Temporary failure in name resolution**
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db
Running Thread: write_data_to_db

**Comment by austinshinkle** [comment]
The error message "socket.gaierror: [Errno -3] Temporary failure in name resolution" occurs when a DNS (Domain Name System) resolution fails temporarily. This means that the system was unable to translate a domain name (e.g., example.com) into an IP address.

Here are some common causes of this error:

Network Connectivity Issues: If your device is not connected to the internet or has unstable network connectivity, DNS resolution might fail.

DNS Server Issues: If the DNS servers configured in your system are down or unreachable, the system won't be able to resolve domain names.

Firewall or Security Software: Sometimes, firewalls or security software can block DNS requests, leading to this error.

Misconfigured DNS Settings: If your DNS settings are incorrect (e.g., wrong DNS server address), your system won't be able to resolve domain names properly.

Temporary Server-Side Issues: The server you're trying to reach might be experiencing issues, causing a temporary DNS failure.

Incorrect Domain Name: If there's a typo or mistake in the domain name you're trying to resolve, it can lead to this error.

Overloaded DNS Cache: A corrupted or overloaded DNS cache on your device or router could cause resolution failures.

To troubleshoot this error, you can try:

Check Network Connection: Ensure you have a stable internet connection.
Flush DNS Cache: On many systems, you can flush the DNS cache using commands like ipconfig /flushdns on Windows or sudo systemd-resolve --flush-caches on Linux.
Change DNS Server: Consider switching to a more reliable DNS server, like Google's DNS (8.8.8.8 and 8.8.4.4) or Cloudflare's DNS (1.1.1.1).
Restart Network Services: Restart your network adapter or services to refresh your connection.
Disable Firewall/Security Software Temporarily: If you suspect security software is interfering, temporarily disable it and see if the issue resolves.
If the issue persists, it might be due to specific network configurations or server issues beyond your control.

**Comment by austinshinkle** [comment]
See socket documentation here: https://docs.python.org/3/library/socket.html#socket.socket.connect

**Comment by austinshinkle** [comment]
Bug has not been seen in over two weeks
