### ISSUE TITLE
get_outside_sensor_data thread crashes

### ISSUE THREAD

**Issue by austinshinkle** [austinshinkle/OB_BreweryMonitorLog#2]
The thread get_outside_sensor_data crashes with this logging output:

Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Exception in thread Thread-2 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 123, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: [Errno 110] Connection timed out
Running Thread: get_sensor_data
Script terminated!
Socket Error Count: 0
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 259, in <module>
    thread_get_outside_sensor_data.start()	
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/threading.py", line 952, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...

**Comment by austinshinkle** [comment]
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-42 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_outside_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-43 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_outside_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-44 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_outside_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-45 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: get_outside_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-46 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_outside_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Exception in thread Thread-47 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_outside_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Exception in thread Thread-48 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
Running Thread: get_sensor_data
Running Thread: get_outside_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
Running Thread: write_data_to_db
Writing values to database...
Running Thread: get_sensor_data
Running Thread: get_sensor_data
^CScript terminated!
Socket Error Count: 0
Exception in thread Thread-49 (get_outside_sensor_data):
Traceback (most recent call last):
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 124, in get_outside_sensor_data
    client_socket.connect((outside_server_ip,outside_server_port))
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashinkl/Repos/OB_BreweryMonitorLog/src/BreweryLog.py", line 161, in get_outside_sensor_data
    except socket.Timeouterror:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socket' has no attribute 'Timeouterror'
